#                                                                        #
# Subroutes configuration for the T3con11Typo3Org package                #
#                                                                        #

- name: 'Setup'
  uriPattern: 'setup(/{@action})'
  defaults:
    @package:    'Conference'
    @controller: 'Setup'
    @action:     'index'
    @format:     'html'

- name: 'Login'
  uriPattern: 'homepage/login.html'
  defaults:
    @package:    'Conference'
    @controller: 'Account\Login'
    @action:     'authenticate'
    @format:     'html'

- name: 'Registration'
  uriPattern: 'homepage/registration.html'
  defaults:
    @package:    'Conference'
    @controller: 'Account\Registration'
    @action:     'index'
    @format:     'html'